### PR TITLE
TAAS-77: Replace Grunt with Gulp

### PR DESCRIPTION
**Pull request by rupl**
## [TAAS-77: Inherit Gulp tasks / workflows from OCHA styleguide](https://humanitarian.atlassian.net/browse/TAAS-77)

As I catch the 🔥 🥔 on these Jekyll sites I'm swapping out the old Grunt workflows for a newer, more capable Gulp workflow. The output is the same, but the following new capabilities/features are added:

* Stability by specifying compatible node.js versions
* All types of watch tasks can run simultaneously: Jekyll, Sass, JS
* Browser-Sync for cross-platform, multi-device development

I also updated the `github-pages` Jekyll gem to use the current version deployed by official GitHub Pages. It's good to keep it in sync so what we see on our local is what we see on the live site.

## Testing

* Follow installation instructions in README (to make sure my docs are correct)

### CODE REVIEW

**Comment by rupl** [comment]
Ok that sounds like a problem with the `uncss` task which is unique to this repo (at least in the company of styleguide/ocha_basic). I believe the dev server not running means the `uncss` can't fetch the files.

@left23 to confirm my suspicion, could you open two terminal windows, run `gulp dev` in one and leave it running, then in the other run `npm run deploy`?

**Comment by left23** [comment]
@rupl Yep, with the dev task running in another terminal, I avoid the errors.

**Comment by rupl** [comment]
ok @left23 this is ready for testing again. Changes from before:

* Deploy script will run server in the background automatically. No change to workflow.
* Modernizr is built during dev/deploy now 😳 
* UnCSS task correctly incorporates Subscribe page while analyzing CSS

**Comment by left23** [comment]
Thanks @rupl. I took it from the top.

At `gulp dev` I get the following error for Modernizr

```
>> Explicitly including these tests:
>> flexbox, mediaqueries, svg

Looking for Modernizr references

>> 2 matches in /var/www/html/taas-data/assets/js/modernizr-output.js
>> supports, svg

>> Ready to build using these settings:
>> setclasses

Building your customized Modernizr{ Error: Error: ENOENT: no such file or directory, open '/var/www/html/taas-data/node_modules/modernizr/lib/../src/setclasses.js'
In module tree:
    modernizr-init

    at Object.fs.openSync (fs.js:646:18)

    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:30099:19
    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:3081:39
    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:3021:25
    at Function.prim.nextTick (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:29929:9)
    at Object.errback (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3020:26)
    at Object.callback (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3006:23)
    at Object.then (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3060:23)
    at build (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:30056:12)
    at runBuild (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:32006:17)
    at Object.execCb (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:1941:33)
  originalError: 
   { Error: ENOENT: no such file or directory, open '/var/www/html/taas-data/node_modules/modernizr/lib/../src/setclasses.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.readFile (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3760:27)
    at Object.readFileAsync (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3774:32)
    at Function.require._cacheReadAsync (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:29948:25)
    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:29506:48
    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:3063:37
    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:3011:25
    at Function.prim.nextTick (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:29929:9)
    at Object.callback (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3010:26)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/var/www/html/taas-data/node_modules/modernizr/lib/../src/setclasses.js',
     fileName: '/var/www/html/taas-data/node_modules/modernizr/lib/../src/setclasses.js',
     moduleTree: [ 'modernizr-init' ] } }
```

**Comment by left23** [comment]
@rupl 
```
lisa@samantha /var/www/html/taas-data ((0627f6f...) *) $ gulp dev:modernizr
[15:36:23] Local environment detected
[15:36:23] Using gulpfile /var/www/html/taas-data/gulpfile.js
[15:36:23] Starting 'dev:modernizr'...

>> Explicitly including these tests:
>> flexbox, mediaqueries, svg

Looking for Modernizr references

>> 2 matches in /var/www/html/taas-data/assets/js/modernizr-output.js
>> supports, svg

>> Ready to build using these settings:
>> setclasses

Building your customized Modernizr{ Error: Error: ENOENT: no such file or directory, open '/var/www/html/taas-data/node_modules/modernizr/lib/../src/setclasses.js'
In module tree:
    modernizr-init

    at Object.fs.openSync (fs.js:646:18)

    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:30099:19
    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:3081:39
    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:3021:25
    at Function.prim.nextTick (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:29929:9)
    at Object.errback (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3020:26)
    at Object.callback (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3006:23)
    at Object.then (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3060:23)
    at build (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:30056:12)
    at runBuild (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:32006:17)
    at Object.execCb (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:1941:33)
  originalError: 
   { Error: ENOENT: no such file or directory, open '/var/www/html/taas-data/node_modules/modernizr/lib/../src/setclasses.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.readFile (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3760:27)
    at Object.readFileAsync (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3774:32)
    at Function.require._cacheReadAsync (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:29948:25)
    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:29506:48
    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:3063:37
    at /var/www/html/taas-data/node_modules/requirejs/bin/r.js:3011:25
    at Function.prim.nextTick (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:29929:9)
    at Object.callback (/var/www/html/taas-data/node_modules/requirejs/bin/r.js:3010:26)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/var/www/html/taas-data/node_modules/modernizr/lib/../src/setclasses.js',
     fileName: '/var/www/html/taas-data/node_modules/modernizr/lib/../src/setclasses.js',
     moduleTree: [ 'modernizr-init' ] } }


```

**Comment by left23** [comment]
@rupl 

```
lisa@samantha /var/www/html/taas-data ((0627f6f...) *) $ node -v && npm -v
v8.11.3
5.6.0
```

**Comment by rupl** [comment]
well I'm not sure the problem.. I have npm `6.2.0` but downgrading did not allow me to reproduce the error.

However it could be argued that constantly rebuilding Modernizr is excessive since our feature tests are pretty tame and Modernizr only has a few releases per year. I only included it because Grunt was originally doing it. I wanted to ship a 1:1 task manager but it's not super necessary.

I'll revert the commits and add a note to the docs reminding people to update the build every once in a blue moon.

**Comment by rupl** [comment]
ok @left23 one more try, hopefully smooth sailing without Modernizr in the mix

**Comment by rupl** [comment]
since Modernizr was the only difference between this repo's tasks and the others, I'm just merging and we'll resolve any issues with follow-ups

**Comment by left23** [comment]
@rupl I tried this again now. All good when running `gulp dev` and `npm run deploy` but I get same error as above when running `gulp dev:modernizr`. Just FYI. No need to hold things up with this, I think.

**Pull request merged**
