### PR TITLE
[OPS-5344] Bump ffi, zip, jekyll.

### PR DESCRIPTION
**Pull request by cafuego**
# NEEDS TESTING

This bump needs testing to ensure nothing breaks.

### CODE REVIEW

**Comment by emmajane** [comment]
@teodorescuserban, @rupl is one of you able to check the updates? Thanks!

**Comment by rupl** [comment]
I'm on it 👍

**Comment by rupl** [comment]
I'll assume that once I merge to master, I can merge it into `gh-pages` and deploy it.

**Comment by rupl** [comment]
this compiled fine on a mac with all the specified versions. merging and will also merge into gh-pages and "deploy"

**Comment by rupl** [comment]
lol I forgot how this repo was set up.. `master` is the GitHub Pages branch... so.. deployed!

**Pull request merged**
